import type { NextPage } from 'next'
import Head from 'next/head'
import { parseCookies } from 'nookies'
import { verify } from 'jsonwebtoken';

import { config } from '../config/jwt';

import { Goals } from '../components/Goals'
import { Navbar } from '../components/Navbar'

const PageGoals: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet"></link>
      </Head>

      <Navbar />
      <Goals />
    </div>
  )
}

export default PageGoals


export function getServerSideProps(ctx: any) {

  const { ['token_user']: token } = parseCookies(ctx);

  if(token) {
    try {
      verify(token, config.secret);
      
    } catch(error) {
      return {
        redirect: {
          destination: '/login',
          permanent: false
        }
      }
    }
  }

  if(!token) {
    return {
      redirect: {
        destination: '/login',
        permanent: false
      }
    }
  }

  return {
    props: {}
  }
}