import type { NextPage } from 'next'
import Head from 'next/head'
import { MyBook } from '../components/MyBooks'

import { Navbar } from '../components/Navbar'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet"></link>
      </Head>

      <Navbar />
      <MyBook />
    </div>
  )
}

export default Home
