import type { NextPage } from 'next'
import Head from 'next/head'

import { PublicLogin } from '../components/Public/Login'

const Login: NextPage = () => {
  return (
    <div>
        <Head>
            <title>MyLivros</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet"></link>
        </Head>

        <PublicLogin />
    </div>
  )
}

export default Login
