import Head from 'next/head'
import { parseCookies } from 'nookies';
import { JwtPayload, verify } from 'jsonwebtoken';

import { instance } from '../config/axios';
import { config } from '../config/jwt';

import { Navbar } from '../components/Navbar';
import { MyBooksSectionsCards } from '../components/MyBooks/Sections/Cards';
import { MyBooksSearch } from '../components/MyBooks/Search';
import { MyBooksSectionsInitial } from '../components/MyBooks/Sections/Initial';
import { MyBooksSectionsNoSection } from '../components/MyBooks/Sections/NoSection';

import { useSections } from '../hooks/Sections';

import { Container } from '../styles/style';

interface RespostType {
  error: boolean,
  message: string,
  results: []
}

interface HomeProps {
  datas: RespostType
}

interface ItemType {
  name_section: string,
  id_section: number
}

export default function Home({ datas }: HomeProps) {

  console.log(datas);

  const { isNoSection } = useSections();

  return (
    <div>
      <Head>
        <title>Sua estante - MyLivros</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href='/favicon.png' />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet"></link>
      </Head>

      <Navbar />

      <Container>
        <MyBooksSearch />
        
        {
          isNoSection ? 
          <MyBooksSectionsNoSection /> :

          datas.results.length === 0 ? 

          <MyBooksSectionsInitial /> :

          datas.results.map((item: ItemType, key) => (
            <MyBooksSectionsCards keyId={key} datas={item} />
          ))
        }

      </Container>
    </div>
  )
}


export async function getServerSideProps(ctx: any) {

  const { ['token_user']: token } = parseCookies(ctx);

  if(token) {
    try {
      const { id } = verify(token, config.secret) as JwtPayload;

      const response = await instance.post('/getSection', { id_user: id });
      const respost: RespostType = await response.data;
      
      return {
        props: {
          datas: respost
        }
      }

    } catch(error) {
      return {
        redirect: {
          destination: '/login',
          permanent: false
        }
      }
    }
  }

  if(!token) {
    return {
      redirect: {
        destination: '/login',
        permanent: false
      }
    }
  }

  return {
    props: {}
  }
}