import type { NextPage } from 'next'
import Head from 'next/head'

import { PublicRegister } from '../components/Public/Register'

const Register: NextPage = () => {
  return (
    <div>
        <Head>
            <title>MyLivros - Cadastro</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet"></link>
        </Head>

        <PublicRegister />
    </div>
  )
}

export default Register
